import pygame

TABLE_COLOR = [0, 186, 143]
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
BACKGROUND = pygame.Surface((SCREEN_WIDTH, SCREEN_HEIGHT))
BACKGROUND.fill(pygame.Color(TABLE_COLOR))
ZERO_POSITION = (0, 0)
CLOCK = pygame.time.Clock()
TIME_DELTA = CLOCK.tick(60) / 1000
BLACK_COLOR = (0, 0, 0)
